<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCharactersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('characters', function (Blueprint $table) {
            $table->increments('id');
            $table->string('character_name');
            $table->integer('player_id');
            $table->string('race');
            $table->string('class');
            $table->integer('class_level');
            $table->string('alignment_moral');
            $table->string('alignment_force');
            $table->string('languages');
            $table->text('background');
            $table->string('image');
            $table->string('homeland');
            $table->string('deity');
            $table->string('size');
            $table->string('gender');
            $table->integer('age');
            $table->string('height');
            $table->integer('weight');
            $table->string('hair');
            $table->string('eyes');
            $table->text('notes');
            $table->integer('str_score');
            $table->integer('str_mod');
            $table->integer('str_temp_score');
            $table->integer('str_temp_mod');
            $table->integer('dex_score');
            $table->integer('dex_mod');
            $table->integer('dex_temp_score');
            $table->integer('dex_temp_mod');
            $table->integer('con_score');
            $table->integer('con_mod');
            $table->integer('con_temp_score');
            $table->integer('con_temp_mod');
            $table->integer('int_score');
            $table->integer('int_mod');
            $table->integer('int_temp_score');
            $table->integer('int_temp_mod');
            $table->integer('wis_score');
            $table->integer('wis_mod');
            $table->integer('wis_temp_score');
            $table->integer('wis_temp_mod');
            $table->integer('char_score');
            $table->integer('char_mod');
            $table->integer('char_temp_score');
            $table->integer('char_temp_mod');
            $table->integer('armor_class_total');
            $table->integer('armor_bonus');
            $table->integer('shield_bonus');
            $table->integer('dex_modifier');
            $table->integer('size_modifier');
            $table->integer('natural_armor');
            $table->integer('deflection');
            $table->integer('misc_armor_mod');
            $table->text('misc_armor_mod_notes');
            $table->integer('touch_armor_class');
            $table->integer('flat_footed_armor_class');
            $table->text('other_ac_mods');
            $table->integer('hit_points_total');
            $table->integer('hit_points_current');
            $table->integer('non_lethal_damage');
            $table->integer('damage_reduction');
            $table->integer('spell_resistance');
            $table->integer('fortitude_total');
            $table->integer('fortitude_base_save');
            $table->integer('fortitude_ability_mod');
            $table->integer('fortitude_magic_mod');
            $table->integer('fortitude_misc_mod');
            $table->integer('fortitude_temp_mod');
            $table->integer('fortitude_other_mods');
            $table->integer('reflex_total');
            $table->integer('reflex_base_save');
            $table->integer('reflex_ability_mod');
            $table->integer('reflex_magic_mod');
            $table->integer('reflex_misc_mod');
            $table->integer('reflex_temp_mod');
            $table->integer('reflex_other_mods');
            $table->integer('will_total');
            $table->integer('will_base_save');
            $table->integer('will_ability_mod');
            $table->integer('will_magic_mod');
            $table->integer('will_misc_mod');
            $table->integer('will_temp_mod');
            $table->integer('will_other_mods');
            $table->text('resistances');
            $table->text('immunities');
            $table->integer('cmd_total');
            $table->integer('cmd_base_attack_bonus');
            $table->integer('cmd_str_mod');
            $table->integer('cmd_dex_mod');
            $table->integer('cmd_size_mod');
            $table->integer('cmd_misc_mods');
            $table->integer('cmd_temp_mods');
            $table->integer('initiative_total');
            $table->integer('initiative_dex_mod');
            $table->integer('initiative_misc_mod');
            $table->integer('base_attack_bonus');
            $table->text('conditional_mods');
            $table->text('conditional_mod_notes');
            $table->integer('speed_base');
            $table->integer('speed_armor');
            $table->integer('speed_fly');
            $table->integer('speed_swim');
            $table->integer('speed_climb');
            $table->integer('speed_burrow');
            $table->integer('speed_temp_mods');
            $table->integer('cmb_total');
            $table->integer('cmb_base_attack_bonus');
            $table->integer('cmb_str_mod');
            $table->integer('cmb_dex_mod');
            $table->integer('cmb_size_mod');
            $table->integer('cmb_misc_mods');
            $table->integer('cmb_temp_mods');
            $table->text('melee_attacks_list');
            $table->text('ranged_attacks_list');
            $table->text('skills_list');
            $table->text('skills_conditional_mods');
            $table->text('skills_conditional_mod_notes');
            $table->integer('xp_total');
            $table->integer('xp_add');
            $table->integer('xp_current_level');
            $table->integer('xp_level_1');
            $table->integer('xp_level_2');
            $table->integer('xp_level_3');
            $table->integer('xp_level_4');
            $table->integer('xp_level_5');
            $table->integer('xp_level_6');
            $table->integer('xp_level_7');
            $table->integer('xp_level_8');
            $table->integer('xp_level_9');
            $table->integer('xp_level_10');
            $table->integer('xp_level_11');
            $table->integer('xp_level_12');
            $table->integer('xp_level_13');
            $table->integer('xp_level_14');
            $table->integer('xp_level_15');
            $table->integer('xp_level_16');
            $table->integer('xp_level_17');
            $table->integer('xp_level_18');
            $table->integer('xp_level_19');
            $table->integer('xp_level_20');
            $table->text('feats');
            $table->text('special_abilities');
            $table->text('traits');
            $table->integer('platinum_pieces');
            $table->integer('gold_pieces');
            $table->integer('silver_pieces');
            $table->integer('copper_pieces');
            $table->text('gems');
            $table->text('art');
            $table->text('other_treasure');
            $table->integer('ac_items_total_bonus');
            $table->integer('ac_items_check_penalty');
            $table->integer('ac_items_spell_failure');
            $table->integer('ac_items_weight');
            $table->text('ac_items_list');
            $table->text('gear_list');
            $table->integer('total_weight');
            $table->text('spelllike_list');
            $table->integer('0_spells_known');
            $table->text('0_spells_list');
            $table->integer('0_spell_dc');
            $table->integer('0_spells_per_day');
            $table->integer('0_bonus_spells');
            $table->integer('1_spells_known');
            $table->text('1_spells_list');
            $table->integer('1_spell_dc');
            $table->integer('1_spells_per_day');
            $table->integer('1_bonus_spells');
            $table->integer('2_spells_known');
            $table->text('2_spells_list');
            $table->integer('2_spell_dc');
            $table->integer('2_spells_per_day');
            $table->integer('2_bonus_spells');
            $table->integer('3_spells_known');
            $table->text('3_spells_list');
            $table->integer('3_spell_dc');
            $table->integer('3_spells_per_day');
            $table->integer('3_bonus_spells');
            $table->integer('4_spells_known');
            $table->text('4_spells_list');
            $table->integer('4_spell_dc');
            $table->integer('4_spells_per_day');
            $table->integer('4_bonus_spells');
            $table->integer('5_spells_known');
            $table->text('5_spells_list');
            $table->integer('5_spell_dc');
            $table->integer('5_spells_per_day');
            $table->integer('5_bonus_spells');
            $table->integer('6_spells_known');
            $table->text('6_spells_list');
            $table->integer('6_spell_dc');
            $table->integer('6_spells_per_day');
            $table->integer('6_bonus_spells');
            $table->integer('7_spells_known');
            $table->text('7_spells_list');
            $table->integer('7_spell_dc');
            $table->integer('7_spells_per_day');
            $table->integer('7_bonus_spells');
            $table->integer('8_spells_known');
            $table->text('8_spells_list');
            $table->integer('8_spell_dc');
            $table->integer('8_spells_per_day');
            $table->integer('8_bonus_spells');
            $table->integer('9_spells_known');
            $table->text('9_spells_list');
            $table->integer('9_spell_dc');
            $table->integer('9_spells_per_day');
            $table->integer('9_bonus_spells');
            $table->text('spells_conditional_mods');
            $table->text('spells_speciality');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('characters');
    }
}
